### ISSUE TITLE
resolver->dnssec(1) without Net::DNS::SEC installed

### ISSUE THREAD

**Issue by schwern** [schwern/Gravatar-URL#4]
The tests are returning `resolver->dnssec(1) without Net::DNS::SEC installed at /Users/schwern/devel/Gravatar-URL/blib/lib/Libravatar/URL.pm line 226.`

**Comment by InfinityGone** [comment]
I wasn't able to replicate this - tests passed without Net::DNS::SEC installed.  Might be related to the Net::DNS::Resolver version?
